package re.neotamia.config.main;

import re.neotamia.config.NTConfig
import re.neotamia.config.adapter.TypeAdapter
import re.neotamia.config.annotation.ConfigHeader
import re.neotamia.config.annotation.ConfigVersion
import re.neotamia.nightconfig.core.serde.DeserializerContext
import re.neotamia.nightconfig.core.serde.NamingStrategy
import re.neotamia.nightconfig.core.serde.SerializerContext
import re.neotamia.nightconfig.core.serde.TypeConstraint
import re.neotamia.nightconfig.core.serde.annotations.SerdeComment
import re.neotamia.nightconfig.core.serde.annotations.SerdeConfig
import re.neotamia.nightconfig.core.serde.annotations.SerdeSkip
import re.neotamia.nightconfig.json.JsonFormat
import re.neotamia.nightconfig.toml.TomlFormat
import re.neotamia.nightconfig.yaml.YamlFormat
import java.nio.file.Path
import java.util.*

enum class Test {
    UWU,
    OWO
}

data class ResourceLocation(var namespace: String, var path: String) {
    constructor(path: String) : this(path.substringBefore(":"), path.substringAfter(":"))
}

@ConfigHeader("This is a sample configuration file.\nGenerated by Kotlin Serialization.")
data class Config(
    @SerdeComment("The name of the configuration")
    val name: String = "Config",
    @ConfigVersion
    val version: Int = 2,
    @SerdeConfig(comments = [SerdeComment("Whether the configuration is enabled")], key = "isEnabled")
    val enabled: Boolean = true,
    @SerdeSkip(SerdeSkip.SkipIf.ALWAYS)
    val decimals: Float = 0.5f,
    val double: Double = 0.123456789,
    val items: List<String> = listOf("item1", "item2", "item3"),
    val settings: Map<String, String> = mapOf("key1" to "value1", "key2" to "value2"),
    val nested: NestedConfig = NestedConfig(),
    val multiline: String = """
        This is a multiline
        string example.
        It preserves line breaks.
    """.trimIndent(),
    val test: Test = Test.OWO,
    val resource: ResourceLocation = ResourceLocation("example:resource_path"),
    val uneVariableOuLeNomPeutEtreTresLong: Boolean = true,
    val toto: Int = 42,
    val titi: Int = 24
) {}

data class NestedConfig(
    val description: String = "Nested Config",
    val count: Int = 10,
    val nested: InnerNestedConfig = InnerNestedConfig()
) {}

data class InnerNestedConfig(
    val flag: Boolean = false,
    val ratio: Double = 3.14
) {}

class ResourceLocationTypeAdapter : TypeAdapter<ResourceLocation, String> {
    override fun valueClass(): Class<ResourceLocation> { return ResourceLocation::class.java }
    override fun resultClass(): Class<String> { return String::class.java }

    override fun serialize(value: ResourceLocation, ctx: SerializerContext): String {
        return "${value.namespace}:${value.path}"
    }

    override fun deserialize(value: String, resultType: Optional<TypeConstraint>, ctx: DeserializerContext): ResourceLocation {
        return ResourceLocation(value)
    }
}

fun main() {
    val ntconfig = NTConfig();
    ntconfig.registerFormat(TomlFormat.instance(), "toml")
    ntconfig.registerFormat(YamlFormat.defaultInstance(), "yaml", "yml")
    ntconfig.registerFormat(JsonFormat.fancyInstance(), "json")
    ntconfig.registerTypeAdapter( ResourceLocationTypeAdapter())
    ntconfig.setNamingStrategy(NamingStrategy.KEBAB_CASE)

    val config = Config()
    config.resource.namespace = "5555555555555555"
    ntconfig.load(Path.of("config.yml"), config);
    println(config)

//    val config = CommentedFileConfig.builder(Path.of("config.yml")).sync().build()
//    val objectSerializer = ObjectSerializer.builder().withSerializerForClass(ResourceLocation::class.java, ResourceLocationTypeAdapter()).build()
//    objectSerializer.serializeFields(Config(), config)
//    println(config)
//
//    config.save()
//    config.load()

//    val deserializer = ObjectDeserializer.builder().build(); //.withDeserializerForClass(String::class.java, ResourceLocation::class.java, ResourceLocationTypeAdapter()).build()
//    val deserializedConfig = Config()
//    deserializedConfig.resource.namespace = "9999999999999999"
//    deserializer.deserializeFields(config, deserializedConfig)
//    println(deserializedConfig.resource)

//    println(config.getOptionalString("decimals").get())
}
